Miw\ClubPadelBundle\Entity\Courts:
    type: entity
    table: courts
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        active:
            type: boolean
            nullable: true
            options:
                default: '1'
    lifecycleCallbacks: {  }
