miw_club_padel_user:
    resource: "@MiwClubPadelBundle/Resources/config/routing/users.yml"
    prefix:   /user

miw_club_padel_reservation:
    resource: "@MiwClubPadelBundle/Resources/config/routing/reservations.yml"
    prefix:   /reservation

miw_club_padel_group:
    resource: "@MiwClubPadelBundle/Resources/config/routing/groups.yml"
    prefix:   /group

miw_club_padel_court:
    resource: "@MiwClubPadelBundle/Resources/config/routing/courts.yml"
    prefix:   /court

miw_club_padel_homepage:
    path:     /hello/{name}
    defaults: { _controller: MiwClubPadelBundle:Default:index }
