court_getAll:
    path:     /
    defaults: { _controller: "MiwClubPadelBundle:Courts:getAll" }
    methods:  GET

court_create:
    path:     /
    defaults: { _controller: "MiwClubPadelBundle:Courts:create" }
    methods:  POST

court_get:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Courts:get" }
    methods:  GET

court_update:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Courts:update" }
    methods:  [POST,PUT]

court_delete:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Courts:delete" }
    methods:  DELETE
