group_getAll:
    path:     /
    defaults: { _controller: "MiwClubPadelBundle:Groups:getAll" }
    methods:  GET

group_create:
    path:     /
    defaults: { _controller: "MiwClubPadelBundle:Groups:create" }
    methods:  POST

group_get:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Groups:get" }
    methods:  GET

group_update:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Groups:update" }
    methods:  [POST, PUT]

group_delete:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Groups:delete" }
    methods:  [POST, DELETE]

group_add_usertogroup:
    path:     /{groupid}/users/{userid}
    defaults: { _controller: "MiwClubPadelBundle:Groups:addUserToGroup" }
    methods:  POST