reservation_getAll:
    path:     /
    defaults: { _controller: "MiwClubPadelBundle:Reservations:getAll" }
    methods:  GET

reservation_create:
    path:     /
    defaults: { _controller: "MiwClubPadelBundle:Reservations:create" }
    methods:  POST

reservation_get:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Reservations:get" }
    methods:  GET

reservation_update:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Reservations:update" }
    methods:  [POST, PUT]

reservation_delete:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Reservations:delete" }
    methods:  DELETE
