user_getAll:
    path:     /
    defaults: { _controller: "MiwClubPadelBundle:Users:getAll" }
    methods:  GET

user_create:
    path:     /
    defaults: { _controller: "MiwClubPadelBundle:Users:create" }
    methods:  POST

user_get:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Users:get" }
    methods:  GET

user_update:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Users:update" }
    methods:  [POST, PUT]

user_delete:
    path:     /{id}
    defaults: { _controller: "MiwClubPadelBundle:Users:delete" }
    methods:  DELETE
